# 01. Importing Libraries

In [12]:
# Import pandas, numpy, and os libraries
# Import libaries
import pandas as pd
import numpy as np
import os

# 02. Importing files

In [13]:
# Import orders_products_merged.pkl
path = r'/Users/brucehickling/Library/CloudStorage/Dropbox/Courses/CareerFoundry/Data Immersion/4_Python/02-2023_Instacart Basket Analysis'

In [14]:
df_ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_merged.pkl'))

In [15]:
df_ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.000000,5,0
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.000000,1,1
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.000000,20,0
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,11.111483,10,0
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.000000,11,1

In [16]:
df_ords_prods_merge.shape

(32404859, 13)

# 03. Create a subset to practice grouping data

In [17]:
# Create a subset, df, of first 1000000 rows of df_ords_prods_merge
df = df_ords_prods_merge[:1000000]

In [18]:
# Check shape, dimensions, and columns names of subset
df.shape

(1000000, 13)

In [19]:
df.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.000000,5,0
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.000000,1,1
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.000000,20,0
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,11.111483,10,0
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.000000,11,1

# 04. Group data with pandas

In [20]:
# Step 1 of grouping - split data into groups by criteria
df.groupby('product_name')

__Groupby() has not output on its own - it creats an object, product_name in this case. You need to apply a function or aggregate data, etc. to achieve an output__

# 05. Aggregating data with agg()

In [21]:
# Group data by 'department_id' and aggregate the 'order_number' data to get the average of orders by department group
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.577493
2                17.320781
3                16.084944
4                17.530458
5                14.763075
6                16.658449
7                17.031590
8                15.076662
9                15.447580
10               18.681852
11               15.447411
12               14.327957
13               16.548642
14               16.960241
15               16.121948
16               17.803851
17               15.593633
18               19.674252
19               16.899756
20               16.255442
21               25.535479

In [23]:
# Aggregate without using agg() - obtain mean of 'order_number' using .mean() function
df.groupby('department_id')['order_number'].mean()

department_id
1     15.577493
2     17.320781
3     16.084944
4     17.530458
5     14.763075
6     16.658449
7     17.031590
8     15.076662
9     15.447580
10    18.681852
11    15.447411
12    14.327957
13    16.548642
14    16.960241
15    16.121948
16    17.803851
17    15.593633
18    19.674252
19    16.899756
20    16.255442
21    25.535479
Name: order_number, dtype: float64

# 06. Aggregating data with transform()

In [24]:
# Create flags with aggregated data - create a loyalty flag
# Use transform() to create a new column containing the maximum frequency of the 'order_number' column, then loc() to create a second column with a flag designating whether a customer is loyal or not.
# Customers with orders > 40 = loyal. Customers with 10 - 40 are regular, and <= 10 are new.
# Step 1-3 for max orders - split the data into groups
df['max_order'] = df.groupby(['user_id'])['order_number'].transform(np.max)

/var/folders/9d/wp_2lptx7pngxs5vccs361_c0000gn/T/ipykernel_94638/2794344778.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['max_order'] = df.groupby(['user_id'])['order_number'].transform(np.max)

In [25]:
df_ords_prods_merge.head(15)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.000000,5,0
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.000000,1,1
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.000000,20,0
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,11.111483,10,0
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.000000,11,1
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,26.000000,7,0
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,30.000000,2,0
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,30.000000,1,0
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,19.000000,1,0
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,15.000000,2,1
10,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,1,5,11,11.111483,1,0
11,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,36,3,13,7.000000,1,0
12,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,38,4,13,7.000000,3,1
13,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,39,2,12,12.000000,4,1
14,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,6,3,10,2.000000,8,0

In [26]:
df.head(100)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.000000,5,0,30
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.000000,1,1,30
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.000000,20,0,5
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,11.111483,10,0,3
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.000000,11,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,Chocolate Sandwich Cookies,61,19,5.8,602103,10831,8,3,11,23.000000,5,0,8
96,1,Chocolate Sandwich Cookies,61,19,5.8,49629,11119,18,1,14,30.000000,1,0,20
97,1,Chocolate Sandwich Cookies,61,19,5.8,317888,11186,13,5,16,2.000000,8,0,23
98,1,Chocolate Sandwich Cookies,61,19,5.8,682486,11243,16,3,13,0.000000,2,0,16
99,1,Chocolate Sandwich Cookies,61,19,5.8,2861386,11448,10,2,15,3.000000,6,0,21

In [27]:
pd.options.display.max_rows = None

In [28]:
df.head(100)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.000000,5,0,30
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.000000,1,1,30
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.000000,20,0,5
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,11.111483,10,0,3
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.000000,11,1,3
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,26.000000,7,0,16
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,30.000000,2,0,3
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,30.000000,1,0,12
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,19.000000,1,0,18
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,15.000000,2,1,18
10,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,1,5,11,11.111483,1,0,6
11,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,36,3,13,7.000000,1,0,41
12,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,38,4,13,7.000000,3,1,41
13,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,39,2,12,12.000000,4,1,41
14,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,6,3,10,2.000000,8,0,9
15,1,Chocolate Sandwich Cookies,61,19,5.8,186761,1494,7,2,8,6.000000,18,1,9
16,1,Chocolate Sandwich Cookies,61,19,5.8,317121,1494,9,5,8,10.000000,12,1,9
17,1,Chocolate Sandwich Cookies,61,19,5.8,200390,1540,4,2,0,7.000000,10,0,28
18,1,Chocolate Sandwich Cookies,61,19,5.8,374436,1540,5,1,21,6.000000,9,1,28
19,1,Chocolate Sandwich Cookies,61,19,5.8,2920553,1540,6,1,0,14.000000,9,1,28
20,1,Chocolate Sandwich Cookies,61,19,5.8,2813049,1540,7,2,2,8.000000,7,1,28
21,1,Chocolate Sandwich Cookies,61,19,5.8,2365998,1540,8,1,23,6.000000,6,1,28
22,1,Chocolate Sandwich Cookies,61,19,5.8,1604797,1540,9,1,3,28.000000,6,1,28
23,1,Chocolate Sandwich Cookies,61,19,5.8,2799665,1540,14,1,14,7.000000,10,1,28
24,1,Chocolate Sandwich Cookies,61,19,5.8,2228851,1540,15,1,14,7.000000,3,1,28
25,1,Chocolate Sandwich Cookies,61,19,5.8,2337422,1540,18,0,21,0.000000,5,1,28
26,1,Chocolate Sandwich Cookies,61,19,5.8,2699008,1540,19,0,22,7.000000,11,1,28
27,1,Chocolate Sandwich Cookies,61,19,5.8,1914830,1540,20,0,22,7.000000,11,1,28
28,1,Chocolate Sandwich Cookies,61,19,5.8,783503,1540,21,0,20,7.000000,5,1,28
29,1,Chocolate Sandwich Cookies,61,19,5.8,2500516,1540,22,0,22,7.000000,15,1,28
30,1,Chocolate Sandwich Cookies,61,19,5.8,716845,1540,24,4,22,3.000000,4,1,28
31,1,Chocolate Sandwich Cookies,61,19,5.8,1955535,1540,25,6,19,16.000000,6,1,28
32,1,Chocolate Sandwich Cookies,61,19,5.8,1424793,1540,27,1,1,5.000000,1,1,28
33,1,Chocolate Sandwich Cookies,61,19,5.8,749498,1540,28,0,21,6.000000,1,1,28
34,1,Chocolate Sandwich Cookies,61,19,5.8,2434812,1598,1,2,12,11.111483,2,0,3
35,1,Chocolate Sandwich Cookies,61,19,5.8,1531889,1598,2,2,10,21.000000,2,1,3
36,1,Chocolate Sandwich Cookies,61,19,5.8,726947,1598,3,4,17,2.000000,3,1,3
37,1,Chocolate Sandwich Cookies,61,19,5.8,627615,1647,1,1,9,11.111483,1,0,9
38,1,Chocolate Sandwich Cookies,61,19,5.8,2507439,1647,4,0,13,18.000000,6,1,9
39,1,Chocolate Sandwich Cookies,61,19,5.8,1152609,1647,6,1,9,8.000000,3,1,9
40,1,Chocolate Sandwich Cookies,61,19,5.8,1048339,1647,8,0,17,30.000000,10,1,9
41,1,Chocolate Sandwich Cookies,61,19,5.8,2818381,1647,9,4,15,25.000000,1,1,9
42,1,Chocolate Sandwich Cookies,61,19,5.8,2722928,2833,1,0,14,11.111483,12,0,1
43,1,Chocolate Sandwich Cookies,61,19,5.8,1482338,2850,7,1,16,9.000000,10,0,21
44,1,Chocolate Sandwich Cookies,61,19,5.8,2311344,2857,24,1,8,10.000000,5,0,24
45,1,Chocolate Sandwich Cookies,61,19,5.8,812943,3010,5,3,10,7.000000,11,0,10
46,1,Chocolate Sandwich Cookies,61,19,5.8,256839,3029,1,2,20,11.111483,8,0,4
47,1,Chocolate Sandwich Cookies,61,19,5.8,2192488,3395,4,2,10,30.000000,7,0,4
48,1,Chocolate Sandwich Cookies,61,19,5.8,207661,3904,1,1,14,11.111483,2,0,1
49,1,Chocolate Sandwich Cookies,61,19,5.8,1394659,4006,2,1,10,7.000000,8,0,40
50,1,Chocolate Sandwich Cookies,61,19,5.8,2353526,4006,3,1,10,7.000000,2,1,40
51,1,Chocolate Sandwich Cookies,61,19,5.8,2269226,4006,5,3,13,7.000000,6,1,40
52,1,Chocolate Sandwich Cookies,61,19,5.8,367316,4006,9,2,11,5.000000,3,1,40
53,1,Chocolate Sandwich Cookies,61,19,5.8,1448367,4006,12,1,11,4.000000,2,1,40
54,1,Chocolate Sandwich Cookies,61,19,5.8,19989,4122,11,2,7,8.000000,1,0,40
55,1,Chocolate Sandwich Cookies,61,19,5.8,2735922,4141,2,0,8,30.000000,2,0,2
56,1,Chocolate Sandwich Cookies,61,19,5.8,2469422,4343,1,1,16,11.111483,9,0,4
57,1,Chocolate Sandwich Cookies,61,19,5.8,3185558,4553,3,5,16,29.000000,1,0,3
58,1,Chocolate Sandwich Cookies,61,19,5.8,350540,4845,6,0,13,12.000000,7,0,6
59,1,Chocolate Sandwich Cookies,61,19,5.8,513100,6866,1,4,15,11.111483,11,0,1
60,1,Chocolate Sandwich Cookies,61,19,5.8,2081405,7275,5,2,23,4.000000,6,0,5
61,1,Chocolate Sandwich Cookies,61,19,5.8,2209807,7669,3,3,15,5.000000,5,0,21
62,1,Chocolate Sandwich Cookies,61,19,5.8,921798,7669,4,1,17,5.000000,6,1,21
63,1,Chocolate Sandwich Cookies,61,19,5.8,2540226,7669,20,1,8,13.000000,3,1,21
64,1,Chocolate Sandwich Cookies,61,19,5.8,2265792,7981,9,2,15,10.000000,2,0,30
65,1,Chocolate Sandwich Cookies,61,19,5.8,3357714,7981,13,0,23,6.000000,1,1,30
66,1,Chocolate Sandwich Cookies,61,19,5.8,1186573,7981,14,2,23,9.000000,1,1,30
67,1,Chocolate Sandwich Cookies,61,19,5.8,3209740,7981,24,2,13,6.000000,2,1,30
68,1,Chocolate Sandwich Cookies,61,19,5.8,138748,7981,30,3,16,8.000000,2,1,30
69,1,Chocolate Sandwich Cookies,61,19,5.8,2027157,8703,34,4,13,1.000000,13,0,98
70,1,Chocolate Sandwich Cookies,61,19,5.8,3052954,8723,4,3,10,7.000000,2,0,35
71,1,Chocolate Sandwich Cookies,61,19,5.8,1486756,8735,8,4,11,21.000000,2,0,8
72,1,Chocolate Sandwich Cookies,61,19,5.8,632514,9293,2,0,12,30.000000,2,0,3
73,1,Chocolate Sandwich Cookies,61,19,5.8,1253470,9293,3,3,13,30.000000,1,1,3
74,1,Chocolate Sandwich Cookies,61,19,5.8,837303,9467,1,0,17,11.111483,11,0,1
75,1,Chocolate Sandwich Cookies,61,19,5.8,2734881,9694,2,0,17,30.000000,3,0,23
76,1,Chocolate Sandwich Cookies,61,19,5.8,2164394,9694,4,4,18,8.000000,2,1,23
77,1,Chocolate Sandwich Cookies,61,19,5.8,3354551,9694,5,4,15,7.000000,1,1,23
78,1,Chocolate Sandwich Cookies,61,19,5.8,1381165,9694,6,4,21,14.000000,2,1,23
79,1,Chocolate Sandwich Cookies,61,19,5.8,2809438,9694,7,4,18,28.000000,1,1,23
80,1,Chocolate Sandwich Cookies,61,19,5.8,425352,9694,10,4,7,16.000000,4,1,23
81,1,Chocolate Sandwich Cookies,61,19,5.8,2453441,9694,14,4,22,1.000000,1,1,23
82,1,Chocolate Sandwich Cookies,61,19,5.8,1189695,9694,15,4,16,14.000000,1,1,23
83,1,Chocolate Sandwich Cookies,61,19,5.8,1759231,9694,16,4,15,7.000000,2,1,23
84,1,Chocolate Sandwich Cookies,61,19,5.8,482648,9694,20,4,13,8.000000,1,1,23
85,1,Chocolate Sandwich Cookies,61,19,5.8,2201348,9694,22,4,14,16.000000,7,1,23
86,1,Chocolate Sandwich Cookies,61,19,5.8,3351592,9848,17,4,18,8.000000,16,0,17
87,1,Chocolate Sandwich Cookies,61,19,5.8,2164672,10113,6,4,18,14.000000,5,0,8
88,1,Chocolate Sandwich Cookies,61,19,5.8,1526735,10315,1,0,16,11.111483,2,0,1
89,1,Chocolate Sandwich Cookies,61,19,5.8,2057892,10479,22,1,16,8.000000,8,0,22
90,1,Chocolate Sandwich Cookies,61,19,5.8,356685,10708,4,2,14,14.000000,15,0,21
91,1,Chocolate Sandwich Cookies,61,19,5.8,1592736,10708,8,2,14,14.000000,9,1,21
92,1,Chocolate Sandwich Cookies,61,19,5.8,3125810,10789,10,0,21,10.000000,1,0,36
93,1,Chocolate Sandwich Cookies,61,19,5.8,846661,10789,11,0,19,14.000000,4,1,36
94,1,Chocolate Sandwich Cookies,61,19,5.8,2363761,10789,16,2,16,4.000000,2,1,36
95,1,Chocolate Sandwich Cookies,61,19,5.8,602103,10831,8,3,11,23.000000,5,0,8
96,1,Chocolate Sandwich Cookies,61,19,5.8,49629,11119,18,1,14,30.000000,1,0,20
97,1,Chocolate Sandwich Cookies,61,19,5.8,317888,11186,13,5,16,2.000000,8,0,23
98,1,Chocolate Sandwich Cookies,61,19,5.8,682486,11243,16,3,13,0.000000,2,0,16
99,1,Chocolate Sandwich Cookies,61,19,5.8,2861386,11448,10,2,15,3.000000,6,0,21

In [29]:
# Deriving columns with loc()
df.loc[df['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'
df.loc[(df['max_order'] <=40) & (df['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'
df.loc[df['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

/var/folders/9d/wp_2lptx7pngxs5vccs361_c0000gn/T/ipykernel_94638/1725853899.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [30]:
# Print the frequency of the 'loyalty_flag' column
df['loyalty_flag'].value_counts(dropna = False)

Regular customer    473070
Loyal customer      287917
New customer        239013
Name: loyalty_flag, dtype: int64

In [31]:
df[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0       138  Regular customer            28
1       138  Regular customer            30
2       709      New customer             2
3       764      New customer             1
4       764      New customer             3
5       777  Regular customer            16
6       825      New customer             3
7       910  Regular customer            12
8      1052  Regular customer            10
9      1052  Regular customer            15
10     1379      New customer             1
11     1480    Loyal customer            36
12     1480    Loyal customer            38
13     1480    Loyal customer            39
14     1494      New customer             6
15     1494      New customer             7
16     1494      New customer             9
17     1540  Regular customer             4
18     1540  Regular customer             5
19     1540  Regular customer             6
20     1540  Regular customer             7
21     1540  Regular customer             8
22     1540  Regular customer             9
23     1540  Regular customer            14
24     1540  Regular customer            15
25     1540  Regular customer            18
26     1540  Regular customer            19
27     1540  Regular customer            20
28     1540  Regular customer            21
29     1540  Regular customer            22
30     1540  Regular customer            24
31     1540  Regular customer            25
32     1540  Regular customer            27
33     1540  Regular customer            28
34     1598      New customer             1
35     1598      New customer             2
36     1598      New customer             3
37     1647      New customer             1
38     1647      New customer             4
39     1647      New customer             6
40     1647      New customer             8
41     1647      New customer             9
42     2833      New customer             1
43     2850  Regular customer             7
44     2857  Regular customer            24
45     3010      New customer             5
46     3029      New customer             1
47     3395      New customer             4
48     3904      New customer             1
49     4006  Regular customer             2
50     4006  Regular customer             3
51     4006  Regular customer             5
52     4006  Regular customer             9
53     4006  Regular customer            12
54     4122  Regular customer            11
55     4141      New customer             2
56     4343      New customer             1
57     4553      New customer             3
58     4845      New customer             6
59     6866      New customer             1